id = "mcp-server-buildkite"
name = "Buildkite MCP"
version = "0.0.2"
description = "Model Context Protocol Server for Buildkite"
schema_version = 1
authors = ["Ben McNicholl <git@benmcnicholl.com>"]
repository = "https://github.com/mcncl/zed-mcp-server-buildkite"

[context_servers.mcp-server-buildkite]
name = "Buildkite MCP Server"
