name: Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      
      - name: Check code
        run: cargo check --all
        
      - name: Run tests
        run: cargo test --all
        
      - name: Check formatting
        run: cargo fmt --all -- --check
        
      - name: Clippy check
        run: cargo clippy --all -- -D warnings
  
  release:
    name: Create GitHub Release
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}